name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🐛
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm these before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of CC Linter
          required: true
        - label: I have read the documentation
          required: true

  - type: input
    id: version
    attributes:
      label: CC Linter Version
      description: What version of CC Linter are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run 'cc-linter lint file.md'
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected the linter to...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, the linter...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      value: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Node.js version: [e.g., 20.9.0]
        - npm version: [e.g., 10.1.0]
        - Shell: [e.g., bash, zsh, cmd]
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: Sample Files
      description: If applicable, provide sample CLAUDE.md content that reproduces the issue
      placeholder: |
        ```markdown
        # Sample CLAUDE.md content that causes the issue
        ```

  - type: textarea
    id: logs
    attributes:
      label: Error Output
      description: Please copy and paste any relevant error output
      render: shell
      placeholder: Paste error output here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here